language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

install:
  - COMPOSER_ROOT_VERSION=dev-master composer install --prefer-source

script:
  - bin/phpspec run
